-- 코드를 입력하세요
SELECT H.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_TOTAL_ORDER
     FROM FIRST_HALF
     GROUP BY FLAVOR) AS H 
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_TOTAL_ORDER
     FROM JULY
     GROUP BY FLAVOR)  AS J
ON H.FLAVOR = J.FLAVOR
ORDER BY H.SUM_TOTAL_ORDER + J.SUM_TOTAL_ORDER DESC
LIMIT 3;