-- 코드를 작성해주세요
SELECT A.YEAR, B.MAX_COLONY - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM 
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, SIZE_OF_COLONY, ID
    FROM ECOLI_DATA) AS A
    JOIN
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR) AS B
    ON A.YEAR = B.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;